export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
export const SET_INGREDIENTS = "SET_INGREDIENTS";
export const FETCH_INGREDIENTS_FAILED = "FETCH_INGREDIENTS_FAILED";

export const PURCHASE_BURGER_STARTED = "PURCHASE_BURGER_STARTED";
export const PURCHASE_BURGER_SUCCEEDED = "PURCHASE_BURGER_SUCCEEDED";
export const PURCHASE_BURGER_FAILED = "PURCHASE_BURGER_FAILED";
