export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
export const SET_INGREDIENTS = "SET_INGREDIENTS";
export const FETCH_INGREDIENTS_FAILED = "FETCH_INGREDIENTS_FAILED";

export const PURCHASE_BURGER_STARTED = "PURCHASE_BURGER_STARTED";
export const PURCHASE_BURGER_SUCCEEDED = "PURCHASE_BURGER_SUCCEEDED";
export const PURCHASE_BURGER_FAILED = "PURCHASE_BURGER_FAILED";
export const INIT_PURCHASING_INFO = "INIT_PURCHASING_INFO";

export const FETCH_ORDERS_STARTED = "FETCH_ORDERS_STARTED";
export const FETCH_ORDERS_SUCCEEDED = "FETCH_ORDERS_SUCCEEDED";
export const FETCH_ORDERS_FAILED = "FETCH_ORDERS_FAILED";

export const AUTHENTICATION_STARTED = "AUTHENTICATION_STARTED";
export const AUTHENTICATION_SUCCEEDED = "AUTHENTICATION_SUCCEEDED";
export const AUTHENTICATION_FAILED = "AUTHENTICATION_FAILED";
export const AUTHENTICATION_SIGN_OUT = "AUTHENTICATION_SIGN_OUT";

export const SET_AUTHENTICATION_REDIRECT_PATH =
  "SET_AUTHENTICATION_REDIRECT_PATH";
